@baseUrl = http://{{$dotenv BACKEND_HOST}}:{{$dotenv BACKEND_PORT}}

### Get one fullsize image

GET {{baseUrl}}/images/3

### Get one thumbnail

GET {{baseUrl}}/images/thumbnails/3

### Get all ids

GET {{baseUrl}}/images/ids

### Get all thumbnails

GET {{baseUrl}}/images/thumbnails/all

### Get metadata from one image

GET {{baseUrl}}/images/3/metadata

### Get metadata from all images

GET {{baseUrl}}/images/all/metadata

### Get nearest neighbours of existing image
POST {{baseUrl}}/faiss/getNN/3
Content-Type: application/json

{
    "k": 6
}

### Get multiple thumbnails by id

POST {{baseUrl}}/images/thumbnails/multiple
Content-Type: application/json

{
    "picture_ids": [
        1, 2, 3, 4, 30
    ]
}

### Get metadata from multiple images

POST {{baseUrl}}/images/multiple/metadata
Content-Type: application/json

{
    "picture_ids": [
        1, 2, 3, 4, 30
    ]
}

### Get size of images in database

GET {{baseUrl}}/images/size
